#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source ~/.zsh-better-npm-completion/zsh-better-npm-completion.plugin.zsh

# Customize to your needs...
source /Users/zx1986/.env
source ~/.aliases

# Git
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

# Ruby
eval "$(rbenv init -)"

# iTerm
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# z
[ -f /usr/local/etc/profile.d/z.sh ] && source /usr/local/etc/profile.d/z.sh

# Fuck
eval $(thefuck --alias)

# Completions
fpath=(/usr/local/share/zsh-completions $fpath)
